# You are given two strings s and t.

# String t is generated by random shuffling string s and then add one more letter at a random position.

# Return the letter that was added to t.

 

# Example 1:

# Input: s = "abcd", t = "abcde"
# Output: "e"
# Explanation: 'e' is the letter that was added.
# Example 2:

# Input: s = "", t = "y"
# Output: "y"


# Solution

from collections import Counter
class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        x = Counter(s)
        y = Counter(t)

        for i in y:
            if x[i] != y[i]:
                return i

solution1 = Solution()
print(solution1.findTheDifference(s = "abcd", t = "abcde"))
